// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx9BZIdRm5Gizj_1TxcK1F_eQX8KPPekE',
    appId: '1:154354017618:web:edb5ae68a5bf09c00b868b',
    messagingSenderId: '154354017618',
    projectId: 'bookly-21459',
    authDomain: 'bookly-21459.firebaseapp.com',
    storageBucket: 'bookly-21459.firebasestorage.app',
    measurementId: 'G-KNY9XEEH8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp0Mr4KSjQTa09jz7Uy1KK3VA2OskvIEI',
    appId: '1:154354017618:android:35d4a45ddd05a83a0b868b',
    messagingSenderId: '154354017618',
    projectId: 'bookly-21459',
    storageBucket: 'bookly-21459.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE0feDDW3ZnWy7V6KnOAiNZCzDr-8DCK8',
    appId: '1:154354017618:ios:bbba17380761f9ed0b868b',
    messagingSenderId: '154354017618',
    projectId: 'bookly-21459',
    storageBucket: 'bookly-21459.firebasestorage.app',
    iosBundleId: 'com.example.booklyAppt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE0feDDW3ZnWy7V6KnOAiNZCzDr-8DCK8',
    appId: '1:154354017618:ios:bbba17380761f9ed0b868b',
    messagingSenderId: '154354017618',
    projectId: 'bookly-21459',
    storageBucket: 'bookly-21459.firebasestorage.app',
    iosBundleId: 'com.example.booklyAppt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx9BZIdRm5Gizj_1TxcK1F_eQX8KPPekE',
    appId: '1:154354017618:web:53ff89df52c88c810b868b',
    messagingSenderId: '154354017618',
    projectId: 'bookly-21459',
    authDomain: 'bookly-21459.firebaseapp.com',
    storageBucket: 'bookly-21459.firebasestorage.app',
    measurementId: 'G-T1T13N0QB3',
  );
}
